const productos = [
  { codigo: "0001", descripcion: "ABRAZADERA DE CAÑO ESCAPE 48MM" },
  { codigo: "0002", descripcion: "ABRAZADERA DE CAÑO ESCAPE 50MM" },
  { codigo: "0003", descripcion: "ABRAZADERA DE CAÑO ESCAPE 54MM" },
  { codigo: "0004", descripcion: "ABRAZADERA DE CAÑO ESCAPE 57MM" },
  { codigo: "0005", descripcion: "ABRAZADERA DE CAÑO ESCAPE 60MM" },
  { codigo: "0006", descripcion: "ABRAZADERA DE CAÑO ESCAPE 63MM" },
  { codigo: "0007", descripcion: "ABRAZADERA DE CAÑO ESCAPE 70MM" },
  { codigo: "0008", descripcion: "ABRAZADERA DE CAÑO ESCAPE 76MM" },
  { codigo: "0009", descripcion: "ABRAZADERA DE CAÑO ESCAPE 89MM" },
  { codigo: "0010", descripcion: "ABRAZADERA DE CAÑO ESCAPE 102MM" },
  { codigo: "0011", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL GOL" },
  { codigo: "0012", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL KA" },
  { codigo: "0013", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL UNO" },
  { codigo: "0014", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL FIESTA" },
  { codigo: "0015", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL CORSA" },
  { codigo: "0016", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL KANGOO" },
  { codigo: "0017", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL BERLINGO" },
  { codigo: "0018", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PARTNER" },
  { codigo: "0019", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL CLIO" },
  { codigo: "0020", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PALIO" },
  { codigo: "0021", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL SIENA" },
  { codigo: "0022", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PEUGEOT 206" },
  { codigo: "0023", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PEUGEOT 207" },
  { codigo: "0024", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PEUGEOT 307" },
  { codigo: "0025", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL 147" },
  { codigo: "0026", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL DUNA" },
  { codigo: "0027", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL FIORINO" },
  { codigo: "0028", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL SPRINTER" },
  { codigo: "0029", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL TRAFIC" },
  { codigo: "0030", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL TRANSIT" },
  { codigo: "0031", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL MASTER" },
  { codigo: "0032", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL DUCATO" },
  { codigo: "0033", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL DAILY" },
  { codigo: "0034", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL KANGOO DIESEL" },
  { codigo: "0035", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL PARTNER DIESEL" },
  { codigo: "0036", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL BERLINGO DIESEL" },
  { codigo: "0037", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL STRADA" },
  { codigo: "0038", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL TORO" },
  { codigo: "0039", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL SAVEIRO" },
  { codigo: "0040", descripcion: "ABRAZADERA DE ESCAPE TIPO ORIGINAL AMAROK" }
];
