const products = [
  {codigo: "WP19930", descripcion: "PASTILLA DE FRENO DELANTERO FIAT UNO/VIVACE"},
  {codigo: "WP18350P", descripcion: "PASTILLA DE FRENO DELANTERO TOYOTA ETIOS"},
  {codigo: "WP16330P", descripcion: "PASTILLA DE FRENO TRASERO COROLLA"},
  {codigo: "WP9900", descripcion: "PASTILLA PEUGEOT/CITROEN"},
  {codigo: "2000/2", descripcion: "TOPE CAPOT VW POLO"},
  {codigo: "2000/5", descripcion: "TOPE CAPOT PEUGEOT"},
  {codigo: "2000/6", descripcion: "TOPE CAPOT FIAT"},
  {codigo: "982108347ZD", descripcion: "TERMINACION BAUL PEUGEOT"},
  {codigo: "SOPRANGER", descripcion: "SOPORTE PARAGOLPE TRASERO RANGER"},
  {codigo: "WP9318", descripcion: "FILTRO DE HABITÁCULO PEUGEOT/CITROEN"},
  {codigo: "WP8440", descripcion: "PASTILLA DE FRENO KANGOO"},
  {codigo: "WP9286", descripcion: "FILTRO FIAT PALIO"},
  {codigo: "WP9166", descripcion: "FILTRO VOLKSWAGEN"},
  {codigo: "0986 BFO 587", descripcion: "FILTRO FORD KA"},
  {codigo: "WP6928", descripcion: "FILTRO KANGOO"},
  {codigo: "0986 BFO 589", descripcion: "FILTRO FORD ECOSPORT"},
  {codigo: "AKX35285", descripcion: "FILTRO OPEL ZAFIRA"},

  // Nuevos productos a partir de acá:
  {codigo: "WP9300", descripcion: "PASTILLA DE FRENO DELANTERA RENAULT CLIO"},
  {codigo: "WP9340", descripcion: "FILTRO DE AIRE TOYOTA HILUX"},
  {codigo: "0986 BFA 123", descripcion: "FILTRO DE ACEITE CHEVROLET CORSA"},
  {codigo: "0986 BFA 567", descripcion: "FILTRO DE ACEITE VOLKSWAGEN SURAN"},
  {codigo: "WP9470", descripcion: "FILTRO HABITÁCULO RENAULT DUSTER"},
  {codigo: "FAP2500", descripcion: "FILTRO DE AIRE FIAT FIORINO"},
  {codigo: "WP9500", descripcion: "FILTRO HABITÁCULO CHEVROLET PRISMA"},
  {codigo: "KL145", descripcion: "FILTRO DE COMBUSTIBLE PEUGEOT 207"},
  {codigo: "WP9600", descripcion: "FILTRO HABITÁCULO CHEVROLET ONIX"},
  {codigo: "WP9650", descripcion: "FILTRO DE AIRE TOYOTA COROLLA"},
  {codigo: "X208", descripcion: "FILTRO DE ACEITE FIAT UNO"},
  {codigo: "KL47", descripcion: "FILTRO DE COMBUSTIBLE CHEVROLET SPIN"},
  {codigo: "WP9700", descripcion: "FILTRO HABITÁCULO CHEVROLET TRACKER"},
  {codigo: "WP9725", descripcion: "FILTRO DE HABITÁCULO PEUGEOT 308"},
  {codigo: "WP9750", descripcion: "FILTRO DE HABITÁCULO FORD FOCUS"},
  {codigo: "WP9800", descripcion: "FILTRO DE HABITÁCULO TOYOTA HILUX"},
  {codigo: "WP9850", descripcion: "FILTRO DE HABITÁCULO HONDA CIVIC"},
  {codigo: "WP9905", descripcion: "FILTRO DE HABITÁCULO FORD KA NUEVO"},
  {codigo: "WP9920", descripcion: "FILTRO DE HABITÁCULO FIAT ARGO"},
  {codigo: "WP9940", descripcion: "FILTRO DE HABITÁCULO CHEVROLET S10"}
];

export default products;
